// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thyfcxcbrvymkjtlxiql.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoeWZjeGNicnZ5bWtqdGx4aXFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDYwODYsImV4cCI6MjA2NDA4MjA4Nn0.1wUeENZJPnwekAsTvLCkNr28OnOiW7Mbw3V1QQ6JQUc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);